In [1]:
#2023210896-王书翰-2.1.2
import numpy as np
from sympy import Matrix
def caculateJ(A):
    A=Matrix(A)
    P,J=A.jordan_form()
    A=np.array(A)
    P=np.array(P)
    J=np.array(J)
    print("A=",A)
    print("J=",J)
def caculateP(A):
    A=Matrix(A)
    P,J=A.jordan_form()
    A=np.array(A)
    P=np.array(P)
    J=np.array(J)
    print("A=",A)
    print("P=",P)
A=np.array([[1,-1,2],[3,-3,6],[2,-2,4]])
caculateJ(A)
A=np.array([[-1,1,0],[-4,3,0],[1,0,2]])
caculateJ(A)
A=np.array([[1,-1,2],[3,-3,6],[2,-2,4]])
caculateP(A)
A=np.array([[1,2,3,4],[0,1,2,3],[0,0,1,2],[0,0,0,1]])
caculateP(A)

A= [[1 -1 2]
 [3 -3 6]
 [2 -2 4]]
J= [[0 0 0]
 [0 0 0]
 [0 0 2]]
A= [[-1 1 0]
 [-4 3 0]
 [1 0 2]]
J= [[1 1 0]
 [0 1 0]
 [0 0 2]]
A= [[1 -1 2]
 [3 -3 6]
 [2 -2 4]]
P= [[1 -2 1/2]
 [1 0 3/2]
 [0 1 1]]
A= [[1 2 3 4]
 [0 1 2 3]
 [0 0 1 2]
 [0 0 0 1]]
P= [[8 12 4 0]
 [0 4 3 0]
 [0 0 2 0]
 [0 0 0 1]]


In [ ]:
#2023210896-王书翰-2.1.3
import numpy as np
def trans_T(X):
    return X+2*X.T
def times(X,k):
    for i in range(k):
        X=trans_T(X)
    return X
X=np.array([[4,-4],[0,-3]])
print(times(X,3))

[[108 -52]
 [-56 -81]]


In [16]:
#2023210896-王书翰-3.1.2
import numpy as np
A = np.array([[2,0,0], [1,1,1],[1,-1,3]])
a1,a2,a3=eigenvalues = np.linalg.eigvals(A)
B=np.array([[1,a3],[0,1]])
C=np.array([np.exp(a3),np.exp(a3)])
x,y=np.linalg.solve(B,C)
fA=x*np.eye(3)+y*A
print("矩阵 A:",A)
print("f(A):",fA)

矩阵 A: [[ 2  0  0]
 [ 1  1  1]
 [ 1 -1  3]]
f(A): [[ 7.3890561  0.         0.       ]
 [ 7.3890561  0.         7.3890561]
 [ 7.3890561 -7.3890561 14.7781122]]


In [ ]:
#2023210896-王书翰-3.2.2
import numpy as np
A = np.array([[4,6,0], [-3,-5,0],[-3,-6,1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
Lambda = np.diag(eigenvalues)
V_inv = np.linalg.inv(eigenvectors)
e_Lambda = np.diag(np.exp(eigenvalues))
e_cost = np.diag(np.cos(eigenvalues))
e_A = eigenvectors @ e_Lambda @ V_inv
cosA= eigenvectors @ e_cost @ V_inv
print("e^A:")
print(e_A)
print("cosA:")
print(cosA)

e^A:
[[ 5.30122837  5.16589309  0.        ]
 [-2.58294655 -2.44761126  0.        ]
 [-2.58294655 -5.16589309  2.71828183]]
cosA:
[[ 1.49675145  1.91289828  0.        ]
 [-0.95644914 -1.37259598  0.        ]
 [-0.95644914 -1.91289828  0.54030231]]


In [46]:
#2023210896-王书翰-3.3.2
import numpy as np
def sine(A,n):
    siA=np.zeros_like(A,dtype=float)
    tempA=A
    cofficient=1
    for i in range(n):
        siA=siA+tempA*cofficient
        tempA=np.dot(tempA,A)
        tempA=np.dot(tempA,A)
        cofficient=cofficient*(-1)/((i+1)*2)*((i+1)*2+1)
    return siA

A = np.array([[3.1415926,0,0,0], [0,-3.1415926,0,0], [0,0,0,1], [0,0,0,0]])
print(sine(A,10))

[[-8.97529585e+09  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  8.97529585e+09  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [67]:
#2023210896-王书翰-3.4.2
import numpy as np
from scipy.linalg import schur, logm
def caculate_ln(A):
    J,P=schur(A)
    lnJ = logm(J)
    P_inv = np.linalg.inv(P)
    result = P@lnJ@P_inv
    result_np = np.array(result, dtype=np.float64)
    print(result_np)
A=np.array([[1,0,0,0],[1,1,0,0],[0,1,1,0],[0,0,1,1]])
caculate_ln(A)
A=np.array([[2,1,0,0],[0,2,0,0],[0,0,1,1],[0,0,0,1]])
caculate_ln(A)

[[ 0.          0.          0.          0.        ]
 [ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 0.33333333 -0.5         1.          0.        ]]
[[0.69314718 0.5        0.         0.        ]
 [0.         0.69314718 0.         0.        ]
 [0.         0.         0.         1.        ]
 [0.         0.         0.         0.        ]]


In [93]:
#2023210896-王书翰-4.1.2
import numpy as np
from scipy.linalg import lu
def ldu_decomposition(A):
    n = A.shape[0]
    L = np.eye(n, dtype=float)
    U = np.copy(A).astype(float)
    D=np.zeros(n)
    for i in range(n):
        pivot =D[i]= U[i, i]
        if(pivot == 0):
            break
        U[i, i:] /= pivot
        for j in range(i + 1, n):
            factor = U[j, i]
            U[j, i:] -= factor * U[i, i:]
            L[j, i] = A[j, i] / pivot
        A=np.linalg.inv(L)@A
    U = np.triu(U, k=1) + np.eye(n)
    D=np.diag(D)
    print("L:", L)
    print("D:", D)
    print("U:", U)
    print(L@D@U)
A = np.array([[2,-1,3], [1,2,1], [2,4,2]])
ldu_decomposition(A)

L: [[1.  0.  0. ]
 [0.5 1.  0. ]
 [1.  2.  1. ]]
D: [[2.  0.  0. ]
 [0.  2.5 0. ]
 [0.  0.  0. ]]
U: [[ 1.  -0.5  1.5]
 [ 0.   1.  -0.2]
 [ 0.   0.   1. ]]
[[ 2. -1.  3.]
 [ 1.  2.  1.]
 [ 2.  4.  2.]]


In [ ]:
#2023210896-王书翰-4.2.2
import numpy as np
def schmidt(vectors):
    vectors = [v.astype(np.float64) for v in vectors]
    orthonormal_vectors = []
    orthogonal_vectors=[]
    k=[]
    for vector in vectors:
        projection = np.zeros_like(vector)
        for v in orthonormal_vectors:
            projection = np.dot(v, vector) *v+projection
        orthogonal_vector = vector - projection
        a=orthogonal_vector
        orthogonal_vectors.append(a)
        k.append(np.linalg.norm(orthogonal_vector))
        orthonormal_vector = orthogonal_vector/np.linalg.norm(orthogonal_vector)
        orthonormal_vectors.append(orthonormal_vector)
    Q=np.column_stack(orthonormal_vectors)
    R=np.eye(A.shape[0],dtype='float')
    C=np.zeros_like(A).astype('float')
    for i in range (A.shape[0]):
        C[i,i]=k[i]
        for j in range(i):
            R[j,i]=np.dot(vectors[i],orthogonal_vectors[j])/np.dot(orthogonal_vectors[j],orthogonal_vectors[j])
    R=C@R
    print("Q:",Q)
    print("R:",R)
    print("QR:",Q@R)
A=np.array([[1,2,2],[2,1,2],[1,2,1]])
vectors = A.T
schmidt(vectors)

Q: [[ 4.08248290e-01  5.77350269e-01  7.07106781e-01]
 [ 8.16496581e-01 -5.77350269e-01 -1.25607397e-15]
 [ 4.08248290e-01  5.77350269e-01 -7.07106781e-01]]
R: [[2.44948974 2.44948974 2.85773803]
 [0.         1.73205081 0.57735027]
 [0.         0.         0.70710678]]
QR: [[1. 2. 2.]
 [2. 1. 2.]
 [1. 2. 1.]]


In [4]:
#2023210896-王书翰-4.3.2
import numpy as np
def full_rank_decomposition(A):
    m, n = A.shape
    augmented_matrix = np.hstack((A, np.eye(m)))
    row_echelon_form = augmented_matrix.copy()
    for i in range(min(m, n)):
        if row_echelon_form[i, i] == 0:
            for k in range(i + 1, m):
                if row_echelon_form[k, i] != 0:
                    row_echelon_form[[i, k]] = row_echelon_form[[k, i]]
                    break
        pivot = row_echelon_form[i, i]
        if pivot != 0:
            row_echelon_form[i] /= pivot
        for k in range(i + 1, m):
            factor = row_echelon_form[k, i]
            row_echelon_form[k] -= factor * row_echelon_form[i]
    P = row_echelon_form[:, n:]
    P_inv = np.linalg.inv(P)
    rank = np.linalg.matrix_rank(A)
    rank=rank-1
    F = P_inv[:, :rank]
    G = row_echelon_form[:rank, :n]
    return F, G
A = np.array([[-1,0,1,2],[1,2,-1,1],[2,2,-2,1]])
B, P = full_rank_decomposition(A)
print("B矩阵:",B)
print("P-1矩阵:",P)
print("BP-1矩阵:",B@P)

B矩阵: [[-1. -0.]
 [ 1.  2.]
 [ 2.  2.]]
P-1矩阵: [[ 1.  -0.  -1.  -2. ]
 [ 0.   1.   0.   1.5]]
BP-1矩阵: [[-1.  0.  1.  2.]
 [ 1.  2. -1.  1.]
 [ 2.  2. -2. -1.]]


In [34]:
#2023210896-王书翰-4.4.2
import numpy as np
A=np.array([[1,0,1],[0,1,1],[0,0,0]])
U, S, VT = np.linalg.svd(A)
Sigma = np.zeros((A.shape[0], A.shape[1]))# 构造对角矩阵 Σ
Sigma[:A.shape[0], :A.shape[0]] = np.diag(S)
print("U 矩阵:")
print(U)
print("\nΣ 矩阵:")
print(Sigma)
print("\nV^T 矩阵:")
print(VT)
print("\n重构矩阵 A:")
print(U @ Sigma @ VT)

U 矩阵:
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

Σ 矩阵:
[[1.73205081 0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         0.        ]]

V^T 矩阵:
[[ 4.08248290e-01  4.08248290e-01  8.16496581e-01]
 [-7.07106781e-01  7.07106781e-01  2.22044605e-16]
 [-5.77350269e-01 -5.77350269e-01  5.77350269e-01]]

重构矩阵 A:
[[ 1.00000000e+00 -6.83580866e-17  1.00000000e+00]
 [-6.83580866e-17  1.00000000e+00  1.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]


In [23]:
#2023210896-王书翰-4.5.4.1
import numpy as np
def full_rank_decomposition(A):
    m, n = A.shape
    augmented_matrix = np.hstack((A, np.eye(m)))
    row_echelon_form = augmented_matrix.copy()
    for i in range(min(m, n)):
        if row_echelon_form[i, i] == 0:
            for k in range(i + 1, m):
                if row_echelon_form[k, i] != 0:
                    row_echelon_form[[i, k]] = row_echelon_form[[k, i]]
                    break
        pivot = row_echelon_form[i, i]
        if pivot != 0:
            row_echelon_form[i] /= pivot
        for k in range(i + 1, m):
            factor = row_echelon_form[k, i]
            row_echelon_form[k] -= factor * row_echelon_form[i]
    P = row_echelon_form[:, n:]
    P_inv = np.linalg.inv(P)
    rank = np.linalg.matrix_rank(A)
    F = P_inv[:, :rank]
    G = row_echelon_form[:rank, :n]
    return F, G

A = np.array([[-1,2,1],[1,0,1],[0,-2,-2],[3,2,5]])
F, G = full_rank_decomposition(A)
print("F矩阵:",F)
print("G矩阵:",G)
F_inv=np.linalg.inv(F.T@F)@F.T
G_inv=G.T@np.linalg.inv(G@G.T)
print("F的伪逆矩阵:",F_inv)
print("G的伪逆矩阵:",G_inv)
print("计算A的伪逆矩阵:",G_inv@F_inv)

F矩阵: [[-1. -0.]
 [ 1.  2.]
 [ 0. -2.]
 [ 3.  8.]]
G矩阵: [[ 1. -2. -1.]
 [ 0.  1.  1.]]
F的伪逆矩阵: [[-0.62068966  0.17241379  0.44827586  0.06896552]
 [ 0.22413793 -0.03448276 -0.18965517  0.0862069 ]]
G的伪逆矩阵: [[ 0.66666667  1.        ]
 [-0.33333333  0.        ]
 [ 0.33333333  1.        ]]
计算A的伪逆矩阵: [[-0.18965517  0.08045977  0.1091954   0.13218391]
 [ 0.20689655 -0.05747126 -0.14942529 -0.02298851]
 [ 0.01724138  0.02298851 -0.04022989  0.1091954 ]]


In [25]:
#2023210896-王书翰-4.5.4.2
import numpy as np
A = np.array([[-1, 0, 1], [2, 0, -2]])
U, S, VT = np.linalg.svd(A)
Sigma = np.zeros((A.shape[0], A.shape[1]))# 构造对角矩阵 Σ
Sigma[:A.shape[0], :A.shape[0]] = np.diag(S)
D = np.zeros((VT.shape[0], U.shape[0]))
for i in range(len(S)):
    if S[i] != 0:
        D[i, i] = 1 / S[i]
print("A的广义逆矩阵为",VT.T@D@U.T)

A的广义逆矩阵为 [[-0.1  0.2]
 [ 0.   0. ]
 [ 0.1 -0.2]]
